apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.azure.yml convert -c -n team-continuous-frustration
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: auth-service
  name: auth-service
  namespace: team-continuous-frustration
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: auth-service
