apiVersion: v1
data:
  01-init.sql: |
{{ .Files.Get "files/01-init.sql" | indent 4 }}
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: {{ .Values.db.name }}
  name: db-cm1
  namespace: {{ .Values.namespace }}
