apiVersion: v1
data:
  01-init.sql: |
    CREATE DATABASE authdb;
    CREATE DATABASE flashcarddb;
    CREATE DATABASE uploaddocumentdb;
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db
  name: db-cm1
  namespace: team-continuous-frustration
