apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.db.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.db.name }}
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_USER
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: {{ .Values.db.image }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: {{ .Values.db.name }}
          ports:
            - containerPort: {{ .Values.db.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.db.resources.requests.cpu | quote }}
              memory: {{ .Values.db.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.db.resources.limits.cpu | quote }}
              memory: {{ .Values.db.resources.limits.memory | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d
              name: db-cm1
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - configMap:
            name: db-cm1
          name: db-cm1
