apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.flashcardService.name }}
    app: {{ .Values.flashcardService.name }}
    monitoring: "true"
  name: {{ .Values.flashcardService.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.flashcardService.port | quote }}
      port: {{ .Values.flashcardService.port }}
      targetPort: {{ .Values.flashcardService.port }}
  selector:
    io.kompose.service: {{ .Values.flashcardService.name }}
