apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.azure.yml convert -c -n team-continuous-frustration
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: flashcard-service
  name: flashcard-service
  namespace: team-continuous-frustration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flashcard-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.azure.yml convert -c -n team-continuous-frustration
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: flashcard-service
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/flashcarddb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
          image: ghcr.io/aet-devops26/team-continuous-frustration/flashcard-service:latest
          name: flashcard-service
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      restartPolicy: Always
