apiVersion: v1
data:
  ollama.sh: |
{{ .Files.Get "files/ollama.sh" | indent 4 }}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: {{ .Values.ollama.name }}
  name: ollama-cm1
  namespace: {{ .Values.namespace }}
