apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.ollama.name }}
  name: {{ .Values.ollama.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.ollama.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.ollama.name }}
    spec:
      containers:
        - command:
            - /bin/sh
            - /ollama.sh
            - --pull-llm
          image: {{ .Values.ollama.image }}
          name: {{ .Values.ollama.name }}
          ports:
            - containerPort: {{ .Values.ollama.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.ollama.resources.requests.cpu | quote }}
              memory: {{ .Values.ollama.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.ollama.resources.limits.cpu | quote }}
              memory: {{ .Values.ollama.resources.limits.memory | quote }}
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama-data
            - mountPath: /ollama.sh
              name: ollama-cm1
              subPath: ollama.sh
      restartPolicy: Always
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-data
        - configMap:
            items:
              - key: ollama.sh
                path: ollama.sh
            name: ollama-cm1
          name: ollama-cm1
