apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.redis.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.redis.name }}
    spec:
      containers:
        - image: {{ .Values.redis.image }}
          name: {{ .Values.redis.name }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
              memory: {{ .Values.redis.resources.limits.memory | quote }}
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
