apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.weaviate.name }}
  name: {{ .Values.weaviate.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.weaviate.port | quote }}
      port: {{ .Values.weaviate.port }}
      targetPort: {{ .Values.weaviate.port }}
    - name: {{ .Values.weaviate.grpcPort | quote }}
      port: {{ .Values.weaviate.grpcPort }}
      targetPort: {{ .Values.weaviate.grpcPort }}
  selector:
    io.kompose.service: {{ .Values.weaviate.name }}
