apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.weaviate.name }}
  name: {{ .Values.weaviate.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.weaviate.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.weaviate.name }}
    spec:
      containers:
        - env:
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: CLUSTER_HOSTNAME
              value: node1
            - name: DEFAULT_VECTORIZER_MODULE
              value: none
            - name: ENABLE_MODULES
              value: text2vec-ollama
            - name: OLLAMA_API_ENDPOINT
              value: http://{{ .Values.ollama.name }}:{{ .Values.ollama.port }}
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: QUERY_DEFAULTS_LIMIT
              value: {{ .Values.weaviate.queryDefaultsLimit | quote }}
          image: {{ .Values.weaviate.image }}
          name: {{ .Values.weaviate.name }}
          ports:
            - containerPort: {{ .Values.weaviate.port }}
              protocol: TCP
            - containerPort: {{ .Values.weaviate.grpcPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.weaviate.resources.requests.cpu | quote }}
              memory: {{ .Values.weaviate.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.weaviate.resources.limits.cpu | quote }}
              memory: {{ .Values.weaviate.resources.limits.memory | quote }}
          volumeMounts:
            - mountPath: /var/lib/weaviate
              name: weaviate-data
      restartPolicy: Always
      volumes:
        - name: weaviate-data
          persistentVolumeClaim:
            claimName: weaviate-data
