apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.webclient.entrypoints: websecure
    traefik.http.routers.webclient.priority: "1"
    traefik.http.routers.webclient.rule: Host(`{{ .Values.ingress.host }}`)
    traefik.http.routers.webclient.tls.certresolver: letsencrypt
    traefik.http.services.webclient.loadbalancer.server.port: {{ .Values.webClient.port | quote }}
  labels:
    io.kompose.service: {{ .Values.webClient.name }}
  name: {{ .Values.webClient.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.webClient.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.webClient.name }}
  template:
    metadata:
      annotations:
        traefik.enable: "true"
        traefik.http.routers.webclient.entrypoints: websecure
        traefik.http.routers.webclient.priority: "1"
        traefik.http.routers.webclient.rule: Host(`{{ .Values.ingress.host }}`)
        traefik.http.routers.webclient.tls.certresolver: letsencrypt
        traefik.http.services.webclient.loadbalancer.server.port: {{ .Values.webClient.port | quote }}
      labels:
        io.kompose.service: {{ .Values.webClient.name }}
    spec:
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.webClient.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.webClient.name }}
          ports:
            - containerPort: {{ .Values.webClient.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.webClient.resources.requests.cpu | quote }}
              memory: {{ .Values.webClient.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.webClient.resources.limits.cpu | quote }}
              memory: {{ .Values.webClient.resources.limits.memory | quote }}
      restartPolicy: Always
