apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.webclient.entrypoints: websecure
    traefik.http.routers.webclient.priority: "1"
    traefik.http.routers.webclient.rule: Host(`{{ .Values.ingress.host }}`)
    traefik.http.routers.webclient.tls.certresolver: letsencrypt
    traefik.http.services.webclient.loadbalancer.server.port: {{ .Values.webClient.port | quote }}
  labels:
    io.kompose.service: {{ .Values.webClient.name }}
  name: {{ .Values.webClient.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.webClient.port | quote }}
      port: {{ .Values.webClient.port }}
      targetPort: {{ .Values.webClient.port }}
  selector:
    io.kompose.service: {{ .Values.webClient.name }}
