apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.webClient.name }}
  name: {{ .Values.webClient.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.webClient.port | quote }}
      port: {{ .Values.webClient.port }}
      targetPort: {{ .Values.webClient.port }}
  selector:
    io.kompose.service: {{ .Values.webClient.name }}
