# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from grpc_server import genai_pb2 as genai__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in genai_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GenaiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateFlashcards = channel.unary_stream(
            "/grpc_genai.GenaiService/GenerateFlashcards",
            request_serializer=genai__pb2.GenerateFlashcardsRequest.SerializeToString,
            response_deserializer=genai__pb2.Flashcard.FromString,
            _registered_method=True,
        )
        self.GenerateExplanation = channel.unary_unary(
            "/grpc_genai.GenaiService/GenerateExplanation",
            request_serializer=genai__pb2.Flashcard.SerializeToString,
            response_deserializer=genai__pb2.Explanation.FromString,
            _registered_method=True,
        )


class GenaiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateFlashcards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GenaiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateFlashcards": grpc.unary_stream_rpc_method_handler(
            servicer.GenerateFlashcards,
            request_deserializer=genai__pb2.GenerateFlashcardsRequest.FromString,
            response_serializer=genai__pb2.Flashcard.SerializeToString,
        ),
        "GenerateExplanation": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateExplanation,
            request_deserializer=genai__pb2.Flashcard.FromString,
            response_serializer=genai__pb2.Explanation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "grpc_genai.GenaiService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "grpc_genai.GenaiService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class GenaiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateFlashcards(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/grpc_genai.GenaiService/GenerateFlashcards",
            genai__pb2.GenerateFlashcardsRequest.SerializeToString,
            genai__pb2.Flashcard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateExplanation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc_genai.GenaiService/GenerateExplanation",
            genai__pb2.Flashcard.SerializeToString,
            genai__pb2.Explanation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
