# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "genai.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bgenai.proto\x12\ngrpc_genai".\n\x19GenerateFlashcardsRequest\x12\x11\n\tupload_id\x18\x01 \x01(\t"c\n\tFlashcard\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\t\x12\x12\n\nsource_ref\x18\x04 \x01(\t\x12\x14\n\x0clast_updated\x18\x05 \x01(\t""\n\x0b\x45xplanation\x12\x13\n\x0b\x65xplanation\x18\x01 \x01(\t2\xaf\x01\n\x0cGenaiService\x12V\n\x12GenerateFlashcards\x12%.grpc_genai.GenerateFlashcardsRequest\x1a\x15.grpc_genai.Flashcard"\x00\x30\x01\x12G\n\x13GenerateExplanation\x12\x15.grpc_genai.Flashcard\x1a\x17.grpc_genai.Explanation"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "genai_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GENERATEFLASHCARDSREQUEST"]._serialized_start = 27
    _globals["_GENERATEFLASHCARDSREQUEST"]._serialized_end = 73
    _globals["_FLASHCARD"]._serialized_start = 75
    _globals["_FLASHCARD"]._serialized_end = 174
    _globals["_EXPLANATION"]._serialized_start = 176
    _globals["_EXPLANATION"]._serialized_end = 210
    _globals["_GENAISERVICE"]._serialized_start = 213
    _globals["_GENAISERVICE"]._serialized_end = 388
# @@protoc_insertion_point(module_scope)
