/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Team Continuous Frustration API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  /** @minLength 3 */
  username: string;
}

export interface RegisterResponse {
  id?: string;
  email?: string;
  username?: string;
}

export interface MeResponse {
  id?: string;
  email?: string;
  username?: string;
}

export type ErrorResponseDetails = { [key: string]: unknown };

export interface ErrorResponse {
  code: string;
  message: string;
  details?: ErrorResponseDetails;
}

/**
 * @summary Register a new user
 */
export const registerUser = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterResponse>> => {
    return axios.default.post(
      `/api/v1/auth/register`,
      registerRequest,options
    );
  }

/**
 * @summary Get the currently authenticated user
 */
export const getMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MeResponse>> => {
    return axios.default.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * @summary Revoke the current session
 */
export const logout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.post(
      `/api/v1/auth/logout`,
      undefined,options
    );
  }

export type RegisterUserResult = AxiosResponse<RegisterResponse>
export type GetMeResult = AxiosResponse<MeResponse>
export type LogoutResult = AxiosResponse<void>
