/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Flashcard Service API
 * Flashcard service endpoints for managing flashcard resources.
 * The service exposes standard CRUD operations and a health check.
 *
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Flashcard {
  /** Unique identifier for the flashcard. */
  id: string;
  /** The flashcard question. */
  question: string;
  /** The flashcard answer. */
  answer: string;
  /** Reference to the source segment or document chunk. */
  source_ref: string;
  /** Human-readable name of the resource the flashcard was generated from (e.g. the uploaded document's file name). */
  source_name?: string;
  /** Timestamp of the last update. */
  last_updated: string;
}

export interface FlashcardCreateRequest {
  /** The flashcard question. */
  question: string;
  /** The flashcard answer. */
  answer: string;
  /** Reference to the source segment or document chunk. */
  source_ref: string;
  /** Human-readable name of the resource the flashcard was generated from (e.g. the uploaded document's file name). */
  source_name?: string;
}

export interface FlashcardUpdateRequest {
  /** The flashcard question. */
  question: string;
  /** The flashcard answer. */
  answer: string;
  /** Reference to the source segment or document chunk. */
  source_ref: string;
}

export interface Error {
  /** Human-readable error message. */
  message: string;
  /** Optional machine-readable error code. */
  code?: string;
}

export type GetFlashcardHealth200 = {
  status: string;
};

/**
 * Returns the service health status.
 * @summary Health check
 */
export const getFlashcardHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetFlashcardHealth200>> => {
    return axios.default.get(
      `/api/v1/flashcards/health`,options
    );
  }

/**
 * Retrieve all flashcards.
 * @summary List flashcards
 */
export const listFlashcards = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Flashcard[]>> => {
    return axios.default.get(
      `/api/v1/flashcards`,options
    );
  }

/**
 * Create a new flashcard resource.
 * @summary Create a flashcard
 */
export const createFlashcard = (
    flashcardCreateRequest: FlashcardCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Flashcard>> => {
    return axios.default.post(
      `/api/v1/flashcards`,
      flashcardCreateRequest,options
    );
  }

/**
 * Retrieve a flashcard by its identifier.
 * @summary Get a flashcard
 */
export const getFlashcardById = (
    flashcardId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Flashcard>> => {
    return axios.default.get(
      `/api/v1/flashcards/${flashcardId}`,options
    );
  }

/**
 * Replace an existing flashcard with updated values.
 * @summary Update a flashcard
 */
export const updateFlashcard = (
    flashcardId: string,
    flashcardUpdateRequest: FlashcardUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Flashcard>> => {
    return axios.default.put(
      `/api/v1/flashcards/${flashcardId}`,
      flashcardUpdateRequest,options
    );
  }

/**
 * Delete a flashcard by its identifier.
 * @summary Delete a flashcard
 */
export const deleteFlashcard = (
    flashcardId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/flashcards/${flashcardId}`,options
    );
  }

export type GetFlashcardHealthResult = AxiosResponse<GetFlashcardHealth200>
export type ListFlashcardsResult = AxiosResponse<Flashcard[]>
export type CreateFlashcardResult = AxiosResponse<Flashcard>
export type GetFlashcardByIdResult = AxiosResponse<Flashcard>
export type UpdateFlashcardResult = AxiosResponse<Flashcard>
export type DeleteFlashcardResult = AxiosResponse<void>
