/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * GenAI service endpoints for flashcard generation.
The /generate-flashcards endpoint streams NDJSON where each line is a Flashcard object.

 * OpenAPI spec version: v1
 */

interface TypedResponse<T> extends Response {
  json(): Promise<T>;
}

export interface Flashcard {
  /** Unique identifier for the flashcard. */
  id: string;
  question: string;
  answer: string;
  /** Reference to the source segment (e.g., page or chunk id). */
  source_ref: string;
  last_updated: string;
}

export interface UploadResponse {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export interface GenerateFlashcardsRequest {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export interface ExplanationResponse {
  explanation: string;
}

export interface Error {
  message: string;
  code?: string;
}

export type PostApiV1GenaiUploadsBody = {
  /** PDF or TXT file to process. */
  file: Blob;
};

/**
 * Upload a PDF or TXT file and receive an upload id.
 * @summary Upload a document for processing
 */
export type postApiV1GenaiUploadsResponse201 = {
  data: UploadResponse
  status: 201
}

export type postApiV1GenaiUploadsResponse400 = {
  data: Error
  status: 400
}

export type postApiV1GenaiUploadsResponse413 = {
  data: Error
  status: 413
}

export type postApiV1GenaiUploadsResponse415 = {
  data: Error
  status: 415
}

export type postApiV1GenaiUploadsResponse500 = {
  data: Error
  status: 500
}
    
export type postApiV1GenaiUploadsResponseSuccess = (postApiV1GenaiUploadsResponse201) & {
  headers: Headers;
};
export type postApiV1GenaiUploadsResponseError = (postApiV1GenaiUploadsResponse400 | postApiV1GenaiUploadsResponse413 | postApiV1GenaiUploadsResponse415 | postApiV1GenaiUploadsResponse500) & {
  headers: Headers;
};

export type postApiV1GenaiUploadsResponse = (postApiV1GenaiUploadsResponseSuccess | postApiV1GenaiUploadsResponseError)

export const getPostApiV1GenaiUploadsUrl = () => {


  

  return `localhost:8080/api/v1/genai/uploads`
}

export const postApiV1GenaiUploads = async (postApiV1GenaiUploadsBody: PostApiV1GenaiUploadsBody, options?: RequestInit): Promise<postApiV1GenaiUploadsResponse> => {
    const formData = new FormData();
formData.append(`file`, postApiV1GenaiUploadsBody.file)

  const res = await fetch(getPostApiV1GenaiUploadsUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiV1GenaiUploadsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1GenaiUploadsResponse
}



/**
 * Provide an upload id and receive a streamed NDJSON response.
Each line is a JSON object with fields id, question, answer, source_ref.

 * @summary Generate flashcards from an uploaded document
 */
export type postApiV1GenaiGenerateFlashcardsResponse200 = {
  stream: TypedResponse<Flashcard>
  status: 200
}

export type postApiV1GenaiGenerateFlashcardsResponse400 = {
  data: Error
  status: 400
}

export type postApiV1GenaiGenerateFlashcardsResponse404 = {
  data: Error
  status: 404
}

export type postApiV1GenaiGenerateFlashcardsResponse500 = {
  data: Error
  status: 500
}
    
export type postApiV1GenaiGenerateFlashcardsResponseSuccess = (postApiV1GenaiGenerateFlashcardsResponse200) & {
  headers: Headers;
};
export type postApiV1GenaiGenerateFlashcardsResponseError = (postApiV1GenaiGenerateFlashcardsResponse400 | postApiV1GenaiGenerateFlashcardsResponse404 | postApiV1GenaiGenerateFlashcardsResponse500) & {
  headers: Headers;
};

export type postApiV1GenaiGenerateFlashcardsResponse = (postApiV1GenaiGenerateFlashcardsResponseSuccess | postApiV1GenaiGenerateFlashcardsResponseError)

export const getPostApiV1GenaiGenerateFlashcardsUrl = () => {


  

  return `localhost:8080/api/v1/genai/generate-flashcards`
}

export const postApiV1GenaiGenerateFlashcards = async (generateFlashcardsRequest: GenerateFlashcardsRequest, options?: RequestInit): Promise<postApiV1GenaiGenerateFlashcardsResponse> => {
  
    const stream = await fetch(getPostApiV1GenaiGenerateFlashcardsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateFlashcardsRequest,)
  }
);
  
  return { status: stream.status, stream, headers: stream.headers } as postApiV1GenaiGenerateFlashcardsResponse
  }



/**
 * Generate an explanation for a given flashcard.
 * @summary Explain a flashcard
 */
export type postApiV1GenaiExplainResponse200 = {
  data: ExplanationResponse
  status: 200
}

export type postApiV1GenaiExplainResponse400 = {
  data: Error
  status: 400
}

export type postApiV1GenaiExplainResponse500 = {
  data: Error
  status: 500
}
    
export type postApiV1GenaiExplainResponseSuccess = (postApiV1GenaiExplainResponse200) & {
  headers: Headers;
};
export type postApiV1GenaiExplainResponseError = (postApiV1GenaiExplainResponse400 | postApiV1GenaiExplainResponse500) & {
  headers: Headers;
};

export type postApiV1GenaiExplainResponse = (postApiV1GenaiExplainResponseSuccess | postApiV1GenaiExplainResponseError)

export const getPostApiV1GenaiExplainUrl = () => {


  

  return `localhost:8080/api/v1/genai/explain`
}

export const postApiV1GenaiExplain = async (flashcard: Flashcard, options?: RequestInit): Promise<postApiV1GenaiExplainResponse> => {
  
  const res = await fetch(getPostApiV1GenaiExplainUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      flashcard,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiV1GenaiExplainResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1GenaiExplainResponse
}
