/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * GenAI service endpoints for flashcard generation. The /generate-flashcards endpoint streams NDJSON where each line is a Flashcard object.
 * OpenAPI spec version: v1
 */

const baseUrl = import.meta.env.VITE_API_BASE_URL ?? '';

interface TypedResponse<T> extends Response {
  json(): Promise<T>;
}

/**
 * Error
 */
export interface Error {
  message: string;
  code?: string | null;
}

/**
 * ExplanationResponse
 */
export interface ExplanationResponse {
  explanation: string;
}

/**
 * Flashcard
 */
export interface Flashcard {
  /** Unique identifier for the flashcard. */
  id: string;
  question: string;
  answer: string;
  /** Reference to the source segment (e.g., page or chunk id). */
  source_ref: string;
  last_updated: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type HealthApiV1GenaiHealthGet200 = { [key: string]: unknown };

export type ApiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostParams = {
  upload_id: string;
};

export type healthApiV1GenaiHealthGetResponse200 = {
  data: HealthApiV1GenaiHealthGet200
  status: 200
}

export type healthApiV1GenaiHealthGetResponseSuccess = (healthApiV1GenaiHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthApiV1GenaiHealthGetResponse = (healthApiV1GenaiHealthGetResponseSuccess)

export const getHealthApiV1GenaiHealthGetUrl = () => {




  return `/api/v1/genai/health`
}

/**
 * @summary Health
 */
export const healthApiV1GenaiHealthGet = async (options?: RequestInit): Promise<healthApiV1GenaiHealthGetResponse> => {

  const res = await fetch(getHealthApiV1GenaiHealthGetUrl(),
    {
      ...options,
      method: 'GET'


    }
  )


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthApiV1GenaiHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthApiV1GenaiHealthGetResponse
}



export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse200 = {
  stream: TypedResponse<Flashcard>
  status: 200
}

export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse400 = {
  data: Error
  status: 400
}

export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse500 = {
  data: Error
  status: 500
}

export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponseSuccess = (apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse200) & {
  headers: Headers;
};
export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponseError = (apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse400 | apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse422 | apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse500) & {
  headers: Headers;
};

export type apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse = (apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponseSuccess | apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponseError)

export const getApiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostUrl = (params: ApiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${baseUrl}/api/v1/genai/generate-flashcards?${stringifiedParams}` : `${baseUrl}/api/v1/genai/generate-flashcards`
}

/**
 * @summary Generate flashcards from an uploaded document
 */
export const apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPost = async (params: ApiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostParams, options?: RequestInit): Promise<apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse> => {

  const stream = await fetch(getApiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostUrl(params),
    {
      ...options,
      method: 'POST'


    }
  );

  return { status: stream.status, stream, headers: stream.headers } as apiV1GenaiGenerateFlashcardsPostApiV1GenaiGenerateFlashcardsPostResponse
}



export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponse200 = {
  data: ExplanationResponse
  status: 200
}

export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponse400 = {
  data: Error
  status: 400
}

export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponse500 = {
  data: Error
  status: 500
}

export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponseSuccess = (apiV1GenaiExplainPostApiV1GenaiExplainPostResponse200) & {
  headers: Headers;
};
export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponseError = (apiV1GenaiExplainPostApiV1GenaiExplainPostResponse400 | apiV1GenaiExplainPostApiV1GenaiExplainPostResponse422 | apiV1GenaiExplainPostApiV1GenaiExplainPostResponse500) & {
  headers: Headers;
};

export type apiV1GenaiExplainPostApiV1GenaiExplainPostResponse = (apiV1GenaiExplainPostApiV1GenaiExplainPostResponseSuccess | apiV1GenaiExplainPostApiV1GenaiExplainPostResponseError)

export const getApiV1GenaiExplainPostApiV1GenaiExplainPostUrl = () => {




  return `/api/v1/genai/explain`
}

/**
 * Generate an explanation for a given flashcard.
 * @summary Explain a flashcard
 */
export const apiV1GenaiExplainPostApiV1GenaiExplainPost = async (flashcard?: Flashcard, options?: RequestInit): Promise<apiV1GenaiExplainPostApiV1GenaiExplainPostResponse> => {

  const res = await fetch(getApiV1GenaiExplainPostApiV1GenaiExplainPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(flashcard)
    }
  )


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiV1GenaiExplainPostApiV1GenaiExplainPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiV1GenaiExplainPostApiV1GenaiExplainPostResponse
}
