/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * GenAI service endpoints for flashcard generation.
The /generate-flashcards endpoint streams NDJSON where each line is a Flashcard object.

 * OpenAPI spec version: v1
 */

interface TypedResponse<T> extends Response {
  json(): Promise<T>;
}

export interface Flashcard {
  /** Unique identifier for the flashcard. */
  id: string;
  question: string;
  answer: string;
  /** Reference to the source segment (e.g., page or chunk id). */
  source_ref: string;
  last_updated: string;
}

export interface UploadResponse {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export interface GenerateFlashcardsRequest {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export interface ExplanationResponse {
  explanation: string;
}

export interface Error {
  message: string;
  code?: string;
}

export type PostGenaiV1UploadsBody = {
  /** PDF or TXT file to process. */
  file: Blob;
};

/**
 * Upload a PDF or TXT file and receive an upload id.
 * @summary Upload a document for processing
 */
export type postGenaiV1UploadsResponse201 = {
  data: UploadResponse
  status: 201
}

export type postGenaiV1UploadsResponse400 = {
  data: Error
  status: 400
}

export type postGenaiV1UploadsResponse413 = {
  data: Error
  status: 413
}

export type postGenaiV1UploadsResponse415 = {
  data: Error
  status: 415
}

export type postGenaiV1UploadsResponse500 = {
  data: Error
  status: 500
}
    
export type postGenaiV1UploadsResponseSuccess = (postGenaiV1UploadsResponse201) & {
  headers: Headers;
};
export type postGenaiV1UploadsResponseError = (postGenaiV1UploadsResponse400 | postGenaiV1UploadsResponse413 | postGenaiV1UploadsResponse415 | postGenaiV1UploadsResponse500) & {
  headers: Headers;
};

export type postGenaiV1UploadsResponse = (postGenaiV1UploadsResponseSuccess | postGenaiV1UploadsResponseError)

export const getPostGenaiV1UploadsUrl = () => {


  

  return `localhost:8080/genai/v1/uploads`
}

export const postGenaiV1Uploads = async (postGenaiV1UploadsBody: PostGenaiV1UploadsBody, options?: RequestInit): Promise<postGenaiV1UploadsResponse> => {
    const formData = new FormData();
formData.append(`file`, postGenaiV1UploadsBody.file)

  const res = await fetch(getPostGenaiV1UploadsUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postGenaiV1UploadsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postGenaiV1UploadsResponse
}



/**
 * Provide an upload id and receive a streamed NDJSON response.
Each line is a JSON object with fields id, question, answer, source_ref.

 * @summary Generate flashcards from an uploaded document
 */
export type postGenaiV1GenerateFlashcardsResponse200 = {
  stream: TypedResponse<Flashcard>
  status: 200
}

export type postGenaiV1GenerateFlashcardsResponse400 = {
  data: Error
  status: 400
}

export type postGenaiV1GenerateFlashcardsResponse404 = {
  data: Error
  status: 404
}

export type postGenaiV1GenerateFlashcardsResponse500 = {
  data: Error
  status: 500
}
    
export type postGenaiV1GenerateFlashcardsResponseSuccess = (postGenaiV1GenerateFlashcardsResponse200) & {
  headers: Headers;
};
export type postGenaiV1GenerateFlashcardsResponseError = (postGenaiV1GenerateFlashcardsResponse400 | postGenaiV1GenerateFlashcardsResponse404 | postGenaiV1GenerateFlashcardsResponse500) & {
  headers: Headers;
};

export type postGenaiV1GenerateFlashcardsResponse = (postGenaiV1GenerateFlashcardsResponseSuccess | postGenaiV1GenerateFlashcardsResponseError)

export const getPostGenaiV1GenerateFlashcardsUrl = () => {


  

  return `localhost:8080/genai/v1/generate-flashcards`
}

export const postGenaiV1GenerateFlashcards = async (generateFlashcardsRequest: GenerateFlashcardsRequest, options?: RequestInit): Promise<postGenaiV1GenerateFlashcardsResponse> => {
  
    const stream = await fetch(getPostGenaiV1GenerateFlashcardsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateFlashcardsRequest,)
  }
);
  
  return { status: stream.status, stream, headers: stream.headers } as postGenaiV1GenerateFlashcardsResponse
  }



/**
 * Generate an explanation for a given flashcard.
 * @summary Explain a flashcard
 */
export type postGenaiV1ExplainResponse200 = {
  data: ExplanationResponse
  status: 200
}

export type postGenaiV1ExplainResponse400 = {
  data: Error
  status: 400
}

export type postGenaiV1ExplainResponse500 = {
  data: Error
  status: 500
}
    
export type postGenaiV1ExplainResponseSuccess = (postGenaiV1ExplainResponse200) & {
  headers: Headers;
};
export type postGenaiV1ExplainResponseError = (postGenaiV1ExplainResponse400 | postGenaiV1ExplainResponse500) & {
  headers: Headers;
};

export type postGenaiV1ExplainResponse = (postGenaiV1ExplainResponseSuccess | postGenaiV1ExplainResponseError)

export const getPostGenaiV1ExplainUrl = () => {


  

  return `localhost:8080/genai/v1/explain`
}

export const postGenaiV1Explain = async (flashcard: Flashcard, options?: RequestInit): Promise<postGenaiV1ExplainResponse> => {
  
  const res = await fetch(getPostGenaiV1ExplainUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      flashcard,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postGenaiV1ExplainResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postGenaiV1ExplainResponse
}
