/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * GenAI service endpoints for flashcard generation.
The /generate-flashcards endpoint streams NDJSON where each line is a Flashcard object.

 * OpenAPI spec version: v1
 */

interface TypedResponse<T> extends Response {
  json(): Promise<T>;
}

export interface Flashcard {
  /** Unique identifier for the flashcard. */
  id: string;
  question: string;
  answer: string;
  /** Reference to the source segment (e.g., page or chunk id). */
  source_ref: string;
  last_updated: string;
}

export interface UploadResponse {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export interface GenerateFlashcardsRequest {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export interface ExplanationResponse {
  explanation: string;
}

export interface Error {
  message: string;
  code?: string;
}

export type PostUploadsBody = {
  /** PDF or TXT file to process. */
  file: Blob;
};

/**
 * Upload a PDF or TXT file and receive an upload id.
 * @summary Upload a document for processing
 */
export type postUploadsResponse201 = {
  data: UploadResponse
  status: 201
}

export type postUploadsResponse400 = {
  data: Error
  status: 400
}

export type postUploadsResponse413 = {
  data: Error
  status: 413
}

export type postUploadsResponse415 = {
  data: Error
  status: 415
}

export type postUploadsResponse500 = {
  data: Error
  status: 500
}

export type postUploadsResponseSuccess = (postUploadsResponse201) & {
  headers: Headers;
};
export type postUploadsResponseError = (postUploadsResponse400 | postUploadsResponse413 | postUploadsResponse415 | postUploadsResponse500) & {
  headers: Headers;
};

export type postUploadsResponse = (postUploadsResponseSuccess | postUploadsResponseError)

export const getPostUploadsUrl = () => {




  return `localhost:8080/uploads`
}

export const postUploads = async (postUploadsBody: PostUploadsBody, options?: RequestInit): Promise<postUploadsResponse> => {
    const formData = new FormData();
formData.append(`file`, postUploadsBody.file)

  const res = await fetch(getPostUploadsUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUploadsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postUploadsResponse
}



/**
 * Provide an upload id and receive a streamed NDJSON response.
Each line is a JSON object with fields id, question, answer, source_ref.

 * @summary Generate flashcards from an uploaded document
 */
export type postGenerateFlashcardsResponse200 = {
  stream: TypedResponse<Flashcard>
  status: 200
}

export type postGenerateFlashcardsResponse400 = {
  data: Error
  status: 400
}

export type postGenerateFlashcardsResponse404 = {
  data: Error
  status: 404
}

export type postGenerateFlashcardsResponse500 = {
  data: Error
  status: 500
}

export type postGenerateFlashcardsResponseSuccess = (postGenerateFlashcardsResponse200) & {
  headers: Headers;
};
export type postGenerateFlashcardsResponseError = (postGenerateFlashcardsResponse400 | postGenerateFlashcardsResponse404 | postGenerateFlashcardsResponse500) & {
  headers: Headers;
};

export type postGenerateFlashcardsResponse = (postGenerateFlashcardsResponseSuccess | postGenerateFlashcardsResponseError)

export const getPostGenerateFlashcardsUrl = () => {




  return `localhost:8080/generate-flashcards`
}

export const postGenerateFlashcards = async (generateFlashcardsRequest: GenerateFlashcardsRequest, options?: RequestInit): Promise<postGenerateFlashcardsResponse> => {

    const stream = await fetch(getPostGenerateFlashcardsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateFlashcardsRequest,)
  }
);

  return { status: stream.status, stream, headers: stream.headers } as postGenerateFlashcardsResponse
  }



/**
 * Generate an explanation for a given flashcard.
 * @summary Explain a flashcard
 */
export type postExplainResponse200 = {
  data: ExplanationResponse
  status: 200
}

export type postExplainResponse400 = {
  data: Error
  status: 400
}

export type postExplainResponse500 = {
  data: Error
  status: 500
}

export type postExplainResponseSuccess = (postExplainResponse200) & {
  headers: Headers;
};
export type postExplainResponseError = (postExplainResponse400 | postExplainResponse500) & {
  headers: Headers;
};

export type postExplainResponse = (postExplainResponseSuccess | postExplainResponseError)

export const getPostExplainUrl = () => {




  return `localhost:8080/explain`
}

export const postExplain = async (flashcard: Flashcard, options?: RequestInit): Promise<postExplainResponse> => {

  const res = await fetch(getPostExplainUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      flashcard,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postExplainResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postExplainResponse
}
