/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Study Service API
 * Study service endpoints for managing decks and flashcard study state.
 * The service creates decks, returns due flashcards for a deck, and lets the server compute due dates from study status updates.
 * Deck ownership is derived from the authenticated user id provided in the request context/header.
 *
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Deck {
  /** Unique identifier for the deck. */
  id: string;
  /** Display name of the deck. */
  name: string;
  /**
     * Tags associated with the deck.
     * @maxItems 10
     */
  tags: string[];
}

export type DeckOverview = Deck & {
  /** Total number of flashcards in the deck. */
  cards: number;
  /** Number of flashcards in the deck due for review today. */
  dueToday: number;
};

export interface DeckCreateRequest {
  /** Display name of the deck. */
  name: string;
  /**
     * Tags associated with the deck.
     * @maxItems 10
     */
  tags: string[];
}

export interface StudyFlashcardCreateRequest {
  /** Identifier of the flashcard. */
  flashcard_id: string;
}

/**
 * Study state reported by the user for a flashcard in a deck.
 */
export type StudyStatus = typeof StudyStatus[keyof typeof StudyStatus];


export const StudyStatus = {
  again: 'again',
  hard: 'hard',
  good: 'good',
  easy: 'easy',
} as const;

export interface StudyStatusUpdateRequest {
  study_status: StudyStatus;
}

export interface StudyDueDateRecord {
  /** Identifier of the deck. */
  deck_id: string;
  /** Identifier of the flashcard. */
  flashcard_id: string;
  /** When the flashcard is next due for review. */
  due_at: string;
  /** Timestamp of the last due date update. */
  updated_at?: string;
}

export interface Error {
  /** Human-readable error message. */
  message: string;
  /** Optional machine-readable error code. */
  code?: string;
}

/**
 * Retrieve all decks owned by the authenticated user.
 * @summary List decks
 */
export const listDecks = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Deck[]>> => {
    return axios.default.get(
      `/api/v1/decks`,options
    );
  }

/**
 * Create a new flashcard deck for the authenticated user.
 * @summary Create a deck
 */
export const createDeck = (
    deckCreateRequest: DeckCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Deck>> => {
    return axios.default.post(
      `/api/v1/decks`,
      deckCreateRequest,options
    );
  }

/**
 * Retrieve all decks owned by the authenticated user, including card counts and due-today counts.
 * @summary List deck overviews
 */
export const listDeckOverviews = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeckOverview[]>> => {
    return axios.default.get(
      `/api/v1/decks/overview`,options
    );
  }

/**
 * Return up to 5 due flashcards for the specified deck.
 * @summary Get due flashcards for a deck
 */
export const getDueFlashcardsForDeck = (
    deckId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyDueDateRecord[]>> => {
    return axios.default.get(
      `/api/v1/decks/${deckId}/study`,options
    );
  }

/**
 * Create a new flashcard study record for the specified deck.
 * @summary Add a flashcard record to a deck
 */
export const createDeckFlashcardRecord = (
    deckId: string,
    studyFlashcardCreateRequest: StudyFlashcardCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyDueDateRecord>> => {
    return axios.default.post(
      `/api/v1/decks/${deckId}/flashcards`,
      studyFlashcardCreateRequest,options
    );
  }

/**
 * Update the study status for a flashcard in a deck. The server determines the next due date.
 * @summary Update a flashcard study status
 */
export const updateFlashcardStudyStatus = (
    deckId: string,
    flashcardId: string,
    studyStatusUpdateRequest: StudyStatusUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyDueDateRecord>> => {
    return axios.default.patch(
      `/api/v1/decks/${deckId}/flashcards/${flashcardId}/study-status`,
      studyStatusUpdateRequest,options
    );
  }

/**
 * Remove the flashcard study record for the specified deck and flashcard.
 * @summary Delete a flashcard from a deck
 */
export const deleteDeckFlashcardRecord = (
    deckId: string,
    flashcardId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/decks/${deckId}/flashcards/${flashcardId}/study-status`,options
    );
  }

export type ListDecksResult = AxiosResponse<Deck[]>
export type CreateDeckResult = AxiosResponse<Deck>
export type ListDeckOverviewsResult = AxiosResponse<DeckOverview[]>
export type GetDueFlashcardsForDeckResult = AxiosResponse<StudyDueDateRecord[]>
export type CreateDeckFlashcardRecordResult = AxiosResponse<StudyDueDateRecord>
export type UpdateFlashcardStudyStatusResult = AxiosResponse<StudyDueDateRecord>
export type DeleteDeckFlashcardRecordResult = AxiosResponse<void>
