/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Document Upload Service API
 * Document Upload service endpoints
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BodyDocumentsUploadPostApiV1DocumentsUploadPost {
  file: Blob;
}

/**
 * Error
 */
export interface Error {
  message: string;
  code?: string | null;
}

export type LocationInner = string | number;

export interface ValidationError {
  loc: LocationInner[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * UploadResponse
 */
export interface UploadResponse {
  /** Identifier for the uploaded file. */
  upload_id: string;
}

export type HealthApiV1DocumentsHealthGet200 = {[key: string]: unknown};

/**
 * @summary Health
 */
export const healthApiV1DocumentsHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthApiV1DocumentsHealthGet200>> => {
    return axios.default.get(
      `/api/v1/documents/health`,options
    );
  }

/**
 * Upload a PDF or TXT file and receive an upload id.
 * @summary Upload a document for processing
 */
export const documentsUploadPostApiV1DocumentsUploadPost = (
    bodyDocumentsUploadPostApiV1DocumentsUploadPost: BodyDocumentsUploadPostApiV1DocumentsUploadPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadResponse>> => {const formData = new FormData();
formData.append('data', bodyDocumentsUploadPostApiV1DocumentsUploadPost)

    return axios.default.post(
      `/api/v1/documents/upload`,
      formData,options
    );
  }

/**
 * Get a document
 * @summary Get a document
 */
export const documentsGetApiV1DocumentsUploadIdGet = (
    uploadId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axios.default.get(
      `/api/v1/documents/${uploadId}`,{
        responseType: 'text',
    ...options,}
    );
  }

export type HealthApiV1DocumentsHealthGetResult = AxiosResponse<HealthApiV1DocumentsHealthGet200>
export type DocumentsUploadPostApiV1DocumentsUploadPostResult = AxiosResponse<UploadResponse>
export type DocumentsGetApiV1DocumentsUploadIdGetResult = AxiosResponse<string>
