name: team-continuous-frustration
description: Helm chart for deploying the team-continuous-frustration platform to Kubernetes
version: 0.1.0
apiVersion: v2
keywords:
  - team-continuous-frustration
sources:
home:
