apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.azure.yml convert -c -n team-continuous-frustration
    kompose.version: 1.38.0 (HEAD)
    traefik.enable: "true"
    traefik.http.middlewares.gateway-compress.compress: "true"
    traefik.http.routers.gateway.entrypoints: websecure
    traefik.http.routers.gateway.middlewares: gateway-compress
    traefik.http.routers.gateway.priority: "10"
    traefik.http.routers.gateway.rule: Host(``) && PathPrefix(`/api`)
    traefik.http.routers.gateway.tls.certresolver: letsencrypt
    traefik.http.services.gateway.loadbalancer.server.port: "8080"
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: team-continuous-frustration
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api-gateway
