apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.azure.yml convert -c -n team-continuous-frustration
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: auth-service
  name: auth-service
  namespace: team-continuous-frustration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.azure.yml convert -c -n team-continuous-frustration
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: FRONTEND_URL
              value: ""
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: JWT_EXPIRATION_MS
              value: "86400000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: SERVER_PORT
              value: "8081"
            - name: SESSION_EXPIRATION_MS
              value: "31536000000"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
          image: ghcr.io/aet-devops26/team-continuous-frustration/auth-service:latest
          name: auth-service
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
