name: Deploy Docker Images

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Azure
      url: 'http://${{ vars.AZURE_PUBLIC_IP }}'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Docker Compose File From Repo to VM Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.AZURE_PUBLIC_IP }}
          username: ${{ vars.AZURE_USER }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          source: "./infra/docker-compose.azure.yml"
          target: /home/${{ vars.AZURE_USER }}/team-continuous-frustration

      - name: SSH to VM and Create .env.prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.AZURE_PUBLIC_IP }}
          username: ${{ vars.AZURE_USER }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            rm -f .env.prod
            touch .env.prod

            echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env.prod
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.prod

            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.prod
            echo "JWT_EXPIRATION_MS=${{ vars.JWT_EXPIRATION_MS }}" >> .env.prod
            echo "SESSION_EXPIRATION_MS=${{ vars.SESSION_EXPIRATION_MS }}" >> .env.prod

            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.prod
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.prod

            echo "FRONTEND_URL=http://${{ vars.AZURE_PUBLIC_IP }}:3000" >> .env.prod
            echo "CORS_ALLOWED_ORIGINS=http://${{ vars.AZURE_PUBLIC_IP }}:3000" >> .env.prod
            echo "VITE_API_BASE_URL=http://${{ vars.AZURE_PUBLIC_IP }}" >> .env.prod

      - name: SSH to VM and Execute Docker-Compose Up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.AZURE_PUBLIC_IP }}
          username: ${{ vars.AZURE_USER }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            echo "Stopping all running containers..."
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            echo "Pruning unused Docker resources..."
            docker system prune -af
            echo "Logging into Docker registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "Starting Docker Compose..."
            cd /home/${{ vars.AZURE_USER }}/team-continuous-frustration/infra
            docker compose -f docker-compose.azure.yml --env-file=/home/${{ vars.AZURE_USER }}/.env.prod up --pull=always -d
